runtime: python311
entrypoint: gunicorn -b :$PORT Plug.wsgi:application

handlers:
- url: /static
  static_dir: static/

- url: /.*
  script: auto

env_variables:
  GS_BUCKET_NAME: "plug-deploy2.appspot.com"
  GOOGLE_APPLICATION_CREDENTIALS: "plug-deploy2-cloud-storge-keys.json"



