# Generated by Django 5.0.6 on 2024-05-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='genre',
            field=models.CharField(choices=[('rap', 'Rap'), ('rnb', 'R&B'), ('pop', 'Pop'), ('house', 'House'), ('edm', 'EDM'), ('rock', 'Rock'), ('jazz', 'Jazz'), ('indie', 'Indie'), ('other', 'Other')], default='Not Specified', max_length=100),
        ),
    ]
