# Generated by Django 5.0.6 on 2024-06-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='genre',
            field=models.CharField(choices=[('Rap', 'Rap'), ('R&b', 'R&B'), ('Pop', 'Pop'), ('House', 'House'), ('Edm', 'EDM'), ('Rock', 'Rock'), ('Jazz', 'Jazz'), ('Indie', 'Indie'), ('Other', 'Other')], default='Not Specified', max_length=100),
        ),
    ]
