# Generated by Django 5.0.6 on 2024-05-27 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_likepost_remove_post_likes_post_likes_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likepost',
            old_name='user',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='likes_count',
            new_name='like_count',
        ),
    ]
